version: '2'
services:
    linkedpipes1:
        build: ./linkedpipes
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
            - ../multiplelp-config/linkedpipes/configuration1.properties:/etl/deploy/configuration.properties
        ports:
            - "18085:18085" # executor.webserver.port
            - "18080:18080" # Webserver & URI dereferencable URI for pipelines + templates
            - "18081:18081" # executor-monitor.webserver.port
            - "12221:12221" # executor-monitor.ftp.port
            - "12223-12230:12223-12230" # Linked Pipes FTP data port
            - "13300:13300" # external.port.start port for external services like Fuseki
            - "19001:9001" # supervisord frontend
    linkedpipes2:
          build: ./linkedpipes
          volumes:
              - ../volumes/linkedpipes2/data:/data
              - ../volumes/linkedpipes2/log:/var/log
              - ../multiplelp-config/linkedpipes/configuration2.properties:/etl/deploy/configuration.properties
          ports:
              - "28085:28085" # executor.webserver.port
              - "28080:28080" # Webserver & URI dereferencable URI for pipelines + templates
              - "28081:28081" # executor-monitor.webserver.port
              - "22221:22221" # executor-monitor.ftp.port
              - "22223-22230:22223-22230" # Linked Pipes FTP data port
              - "23300:23300" # external.port.start port for external services like Fuseki
              - "29001:9001" # supervisord frontend
    fuseki1:
        build: ./fuseki
        volumes:
            - ../volumes/fuseki1/log:/var/log
            - ../volumes/fuseki1/data:/data
        ports:
            - "13030:3030"
            - "13901:9001" # supervisord frontend
    fuseki2:
        build: ./fuseki
        volumes:
            - ../volumes/fuseki2/log:/var/log
            - ../volumes/fuseki2/data:/data
        ports:
            - "23030:3030"
            - "23901:9001" # supervisord frontend







